spring:
  application:
    name: panda-server
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.panda.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8080

panda:
  jwt:
    secret-key: 12345678901234567890123456789012
    ttl: 604800000
    token-name: Authorization
